name = "ChiralGeometrogenesis"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ChiralGeometrogenesis"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[require]]
name = "PhysLean"
scope = "HEPLean"
rev = "master"

[[lean_lib]]
name = "ChiralGeometrogenesis"
